### ISSUE TITLE
Implement Focusable

### ISSUE THREAD

**Issue by erikhofer** [parttio/tinymce-for-flow#18] opened 2023-08-08 09:53 UTC
The component already has a `focus()` method. It would be really useful if it implemented `com.vaadin.flow.component.Focusable<T>`. I think in this case, support for blurring needs to be added.

**Comment by mstahv** [comment] 2023-08-08 14:14
Do you happen to need the blur() method? Didn't quickly find a way to implement that in TinyMC JS widget.

**Comment by erikhofer** [comment] 2023-08-08 15:40
Oh, interesting that `blur` is not exposed just like `focus`. I think for us this would be okay. What would be helpful, however, is implementing  `BlurNotifier.addBlurListener()` that comes with `Focusable`. This would need to be wired to the `blur` event which looks possible: https://www.tiny.cloud/docs/tinymce/6/events/#supported-browser-native-events

**Comment by mstahv** [comment] 2023-08-08 15:58
Pushed a branch where Focusable is implemented. Known issues:

 * blur() not supported (as discussed), throws UOE
 * blur listener is fired also when opening menus in the editor
 
 I wonder how the latter should work and if it can be changed easily. If your think this would be helpful, then I'm fine committing that to the main branch.

**Comment by mstahv** [comment] 2023-08-08 16:01
Also there seems to be a bug(or regression) with Chrome, Safari works fine 😬

**Comment by erikhofer** [comment] 2023-08-15 07:38
> Pushed a branch where Focusable is implemented. Known issues:
> 
>   * blur() not supported (as discussed), throws UOE
> 
>   * blur listener is fired also when opening menus in the editor
> 
> 
> I wonder how the latter should work and if it can be changed easily. If your think this would be helpful, then I'm fine committing that to the main branch.

Thanks for the effort :) Looks good to me so far.
I guess the behaviour is correct because when you open a menu, the focus of the text area (as indicated by the blinking cursor) is actually lost.

**Comment by mstahv** [comment] 2023-08-15 07:43
The regression pushed me on framework development and I spent basically the rest of my week there 😬 Some very heavy stuff: https://github.com/vaadin/flow/pull/17410

I hope I can get that PR to framework soon and then push out a new version with this and vastly improved content synchronisation.

**Comment by mstahv** [comment] 2023-09-06 10:48
Fixed in 4.0.1 (currently syncing to maven central). Needs Vaadin 24.1.8 or newer!

**Closed as completed by mstahv** 2023-09-06 10:48 UTC

**Comment by mstahv** [comment] 2023-09-06 16:18
Better make that 4.0.2, 4.0.1 had a regression that it didn't fire value change when formatting was changed via buttons/menus.

**Comment by erikhofer** [comment] 2023-09-07 20:03
@mstahv Thank you! :)
